name: notibot-service

replicaCount: 1               # HPA 안 쓸 경우 수동 복제 수 지정

nodeSelector:
  nodegroup-type: first

image:
  repository: 879381276515.dkr.ecr.ap-northeast-2.amazonaws.com/aigongbu/service-images
  tag: 5912e12eaff22aef1ff7ec317a9ba3e85a48b117
  pullPolicy: IfNotPresent

containerPort: 80

resources:                    # 오토 스케일 기반 마련
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 200m
    memory: 512Mi

service:
  protocol: TCP
  port: 80
  targetPort: 80
  type: ClusterIP

hpa:
  enabled: false
