apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notibot-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Team-Study-Bridge/notibot-service
    targetRevision: main
    path: helm/notibot-service
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false  # default 네임스페이스 사용 시 false